target = {
    0: 'batting_points_shifted', 
    1: 'fantasy_points_shifted', 
    2: 'bowling_points_shifted'
}

features = {
    'ODI' : {
        0: ['sixes_last_n','strike_rate_last_n', 'hundreds_last_n','fifties_last_n','runs_last_n','fours_last_n', 'cumulative_average_batting', 'days_since_last_match', 'cumulative_top_11_count', 'sixes_scored_till_date_against_opponent_by_this_player', 'runs_scored_till_date_against_opponent_by_this_player', 'fours_scored_till_date_against_opponent_by_this_player', 'runs_scored_till_date_on_this_venue_by_this_player', 'fours_scored_till_date_on_this_venue_by_this_player', 'sixes_scored_till_date_on_this_venue_by_this_player', 'weighted_score_last_2_months'],
        1: ['wickets_last_n', 'maiden_overs_last_n', 'overs_bowled_last_n', 'extras_given_last_n', 'runs_given_last_n','sixes_last_n','strike_rate_last_n', 'hundreds_last_n','fifties_last_n','runs_last_n','fours_last_n', 'cumulative_average_batting', 'cumulative_average_bowling', 'days_since_last_match', 'cumulative_top_11_count', 'sixes_scored_till_date_against_opponent_by_this_player', 'runs_scored_till_date_against_opponent_by_this_player', 'fours_scored_till_date_against_opponent_by_this_player', 'runs_scored_till_date_on_this_venue_by_this_player', 'fours_scored_till_date_on_this_venue_by_this_player', 'sixes_scored_till_date_on_this_venue_by_this_player', 'weighted_score_last_2_months', 'wickets_taken_till_date_against_opponent_by_this_player', 'cumulative_avg_runs_given', 'wickets_taken_till_date_on_this_venue_by_this_player', 'cumulative_avg_runs_given_venue' ],
        2: ['wickets_last_n', 'maiden_overs_last_n', 'overs_bowled_last_n', 'extras_given_last_n', 'runs_given_last_n', 'cumulative_average_bowling', 'days_since_last_match', 'cumulative_top_11_count', 'wickets_taken_till_date_against_opponent_by_this_player', 'cumulative_avg_runs_given', 'wickets_taken_till_date_on_this_venue_by_this_player', 'cumulative_avg_runs_given_venue']
    },
    'T20' : {
        0: ['sixes_last_n','strike_rate_last_n', 'hundreds_last_n','fifties_last_n','runs_last_n','fours_last_n', 'cumulative_average_batting', 'days_since_last_match', 'cumulative_top_11_count', 'sixes_scored_till_date_against_opponent_by_this_player', 'runs_scored_till_date_against_opponent_by_this_player', 'fours_scored_till_date_against_opponent_by_this_player', 'runs_scored_till_date_on_this_venue_by_this_player', 'fours_scored_till_date_on_this_venue_by_this_player', 'sixes_scored_till_date_on_this_venue_by_this_player', 'weighted_score_last_2_months'],
        1: ['wickets_last_n', 'maiden_overs_last_n', 'overs_bowled_last_n', 'extras_given_last_n', 'runs_given_last_n','sixes_last_n','strike_rate_last_n', 'hundreds_last_n','fifties_last_n','runs_last_n','fours_last_n', 'cumulative_average_batting', 'cumulative_average_bowling', 'days_since_last_match', 'cumulative_top_11_count', 'sixes_scored_till_date_against_opponent_by_this_player', 'runs_scored_till_date_against_opponent_by_this_player', 'fours_scored_till_date_against_opponent_by_this_player', 'runs_scored_till_date_on_this_venue_by_this_player', 'fours_scored_till_date_on_this_venue_by_this_player', 'sixes_scored_till_date_on_this_venue_by_this_player', 'weighted_score_last_2_months', 'wickets_taken_till_date_against_opponent_by_this_player', 'cumulative_avg_runs_given', 'wickets_taken_till_date_on_this_venue_by_this_player', 'cumulative_avg_runs_given_venue'],
        2: ['wickets_last_n', 'maiden_overs_last_n', 'overs_bowled_last_n', 'extras_given_last_n', 'runs_given_last_n', 'cumulative_average_bowling', 'days_since_last_match', 'cumulative_top_11_count', 'wickets_taken_till_date_against_opponent_by_this_player', 'cumulative_avg_runs_given', 'wickets_taken_till_date_on_this_venue_by_this_player', 'cumulative_avg_runs_given_venue']
    },
    'multi_day' : {
        0 : ['sixes_last_n', 'hundreds_last_n','fifties_last_n','runs_last_n','fours_last_n', 'cumulative_average_batting', 'days_since_last_match', 'cumulative_top_11_count', 'sixes_scored_till_date_against_opponent_by_this_player', 'runs_scored_till_date_against_opponent_by_this_player', 'fours_scored_till_date_against_opponent_by_this_player', 'runs_scored_till_date_on_this_venue_by_this_player', 'fours_scored_till_date_on_this_venue_by_this_player', 'sixes_scored_till_date_on_this_venue_by_this_player', 'weighted_score_last_2_months', 'fatigue_score', 'winning_exponentially_decayed_batting_points', 'batting_points_decayed', 'batting_points_exp_avg'],
        1 : ['wickets_last_n', 'maiden_overs_last_n', 'overs_bowled_last_n', 'extras_given_last_n', 'runs_given_last_n','sixes_last_n', 'hundreds_last_n','fifties_last_n','runs_last_n','fours_last_n', 'cumulative_average_batting', 'cumulative_average_bowling', 'days_since_last_match', 'cumulative_top_11_count', 'sixes_scored_till_date_against_opponent_by_this_player', 'runs_scored_till_date_against_opponent_by_this_player', 'fours_scored_till_date_against_opponent_by_this_player', 'runs_scored_till_date_on_this_venue_by_this_player', 'fours_scored_till_date_on_this_venue_by_this_player', 'sixes_scored_till_date_on_this_venue_by_this_player', 'weighted_score_last_2_months', 'wickets_taken_till_date_against_opponent_by_this_player', 'cumulative_avg_runs_given', 'wickets_taken_till_date_on_this_venue_by_this_player', 'cumulative_avg_runs_given_venue', 'fatigue_score', 'winning_exponentially_decayed_bowling_points', 'bowling_points_decayed', 'winning_exponentially_decayed_batting_points', 'batting_points_decayed', 'BPS', 'batting_points_exp_avg', 'bowling_points_exp_avg'],
        2 : ['wickets_last_n', 'maiden_overs_last_n', 'overs_bowled_last_n', 'extras_given_last_n', 'runs_given_last_n', 'cumulative_average_bowling', 'days_since_last_match', 'cumulative_top_11_count', 'wickets_taken_till_date_against_opponent_by_this_player', 'cumulative_avg_runs_given', 'wickets_taken_till_date_on_this_venue_by_this_player', 'cumulative_avg_runs_given_venue', 'winning_exponentially_decayed_bowling_points', 'bowling_points_decayed', 'bowling_points_exp_avg']
    }
}

